### ISSUE TITLE
MedusaBackup missing

### ISSUE THREAD

**Issue by Diskutant** [sentient06/Medusa#4]
I just wanted to build Medusa out of curiosity. But there is a shellScript defined somewhere that wants to run ~/Library/MedusaBackup

Of course I don't have that. And I can't find where in XCode 6.1.1 I can configure that script. 
Hope you can help me here. Thanks!

**Comment by sentient06** [comment]
Hi Diskutant,

Sorry I took a long time to check on Medusa again.
This is a script I use to clear some Medusa information saved on OSX so I can avoid errors with the help area. You can change it on the project details area in XCode, clicking in the "Build Phases" tab, then locating "Run Script". You can tick the "Run script only when installing" checkbox or you can delete it altogether.

**Comment by Metal-Snake** [comment]
Hi sentient06,

sorry to also took way too long to reply here. Just never came around to do anything related to Mac emulation.
I just loaded your latest source code, works fine now. Thanks!

PS.: From what I saw so far, it looks really good. 
Do you plan to update the tools to include qemu (as SheepShaver won't last too long anymore)?

PPS.: In the repository description and in the readme you link to http://medusa.mariot.me.uk but that seems to be dead.
